/**
 * Firestore Security Rules Test Suite (Dirty Dozen Verification)
 * Verifies that all 12 adversarial payloads in security_spec.md return PERMISSION_DENIED.
 */

export interface SimulatedRuleContext {
  auth: {
    uid: string;
    token: {
      email: string;
      email_verified: boolean;
    };
  } | null;
  requestTime: string;
  existingDocs: Record<string, any>;
}

export const DIRTY_DOZEN_TEST_CASES = [
  {
    id: 1,
    name: 'Identity Spoofing on User Create',
    path: '/users/user_B',
    op: 'create',
    authUid: 'user_A',
    emailVerified: true,
    payload: {
      uid: 'user_B',
      email: 'a@gmail.com',
      displayName: 'User A',
      photoURL: '',
      userType: 'student',
      institutionName: 'MIT',
      studentId: '123',
      createdAt: 'SERVER_TIME',
      updatedAt: 'SERVER_TIME',
    },
    expected: 'PERMISSION_DENIED',
  },
  {
    id: 2,
    name: 'Unverified Email Write',
    path: '/users/user_A',
    op: 'create',
    authUid: 'user_A',
    emailVerified: false,
    payload: {
      uid: 'user_A',
      email: 'a@gmail.com',
      displayName: 'User A',
      photoURL: '',
      userType: 'student',
      institutionName: 'MIT',
      studentId: '123',
      createdAt: 'SERVER_TIME',
      updatedAt: 'SERVER_TIME',
    },
    expected: 'PERMISSION_DENIED',
  },
  {
    id: 3,
    name: 'Shadow Field Injection on User Create',
    path: '/users/user_A',
    op: 'create',
    authUid: 'user_A',
    emailVerified: true,
    payload: {
      uid: 'user_A',
      email: 'a@gmail.com',
      displayName: 'User A',
      photoURL: '',
      userType: 'student',
      institutionName: 'MIT',
      studentId: '123',
      isAdmin: true,
      createdAt: 'SERVER_TIME',
      updatedAt: 'SERVER_TIME',
    },
    expected: 'PERMISSION_DENIED',
  },
  {
    id: 4,
    name: 'PII Lateral Read',
    path: '/users/user_A',
    op: 'get',
    authUid: 'user_B',
    emailVerified: true,
    payload: null,
    expected: 'PERMISSION_DENIED',
  },
  {
    id: 5,
    name: 'Immutable Field Tampering on User Update',
    path: '/users/user_A',
    op: 'update',
    authUid: 'user_A',
    emailVerified: true,
    payload: {
      uid: 'user_A',
      email: 'a@gmail.com',
      displayName: 'User A',
      photoURL: '',
      userType: 'student',
      institutionName: 'MIT',
      studentId: '123',
      createdAt: 'TAMPERED_TIME',
      updatedAt: 'SERVER_TIME',
    },
    expected: 'PERMISSION_DENIED',
  },
  {
    id: 6,
    name: 'Client Timestamp Forgery',
    path: '/users/user_A',
    op: 'create',
    authUid: 'user_A',
    emailVerified: true,
    payload: {
      uid: 'user_A',
      email: 'a@gmail.com',
      displayName: 'User A',
      photoURL: '',
      userType: 'student',
      institutionName: 'MIT',
      studentId: '123',
      createdAt: '2099-01-01T00:00:00Z',
      updatedAt: 'SERVER_TIME',
    },
    expected: 'PERMISSION_DENIED',
  },
  {
    id: 7,
    name: 'Value Poisoning on User Update',
    path: '/users/user_A',
    op: 'update',
    authUid: 'user_A',
    emailVerified: true,
    payload: {
      uid: 'user_A',
      email: 'a@gmail.com',
      displayName: 'User A',
      photoURL: '',
      userType: 'superadmin',
      institutionName: 'MIT',
      studentId: '123',
      createdAt: 'SERVER_TIME',
      updatedAt: 'SERVER_TIME',
    },
    expected: 'PERMISSION_DENIED',
  },
  {
    id: 8,
    name: 'ID Poisoning / Resource Exhaustion',
    path: '/users/user_A/scans/bad$id!',
    op: 'create',
    authUid: 'user_A',
    emailVerified: true,
    payload: {
      id: 'bad$id!',
      ownerId: 'user_A',
      title: 'Essay',
      wordCount: 100,
      overallScore: 95,
      plagiarismScore: 2,
      paraphraseScore: 3,
      aiScore: 0,
      originalScore: 95,
      summary: 'Clean',
      payloadJson: '{}',
      createdAt: 'SERVER_TIME',
    },
    expected: 'PERMISSION_DENIED',
  },
  {
    id: 9,
    name: 'Orphaned Scan Write without Parent User',
    path: '/users/user_Ghost/scans/scan_1',
    op: 'create',
    authUid: 'user_Ghost',
    emailVerified: true,
    payload: {
      id: 'scan_1',
      ownerId: 'user_Ghost',
      title: 'Essay',
      wordCount: 100,
      overallScore: 95,
      plagiarismScore: 2,
      paraphraseScore: 3,
      aiScore: 0,
      originalScore: 95,
      summary: 'Clean',
      payloadJson: '{}',
      createdAt: 'SERVER_TIME',
    },
    expected: 'PERMISSION_DENIED',
  },
  {
    id: 10,
    name: 'Cross-Tenant Scan Creation',
    path: '/users/user_B/scans/scan_1',
    op: 'create',
    authUid: 'user_A',
    emailVerified: true,
    payload: {
      id: 'scan_1',
      ownerId: 'user_A',
      title: 'Essay',
      wordCount: 100,
      overallScore: 95,
      plagiarismScore: 2,
      paraphraseScore: 3,
      aiScore: 0,
      originalScore: 95,
      summary: 'Clean',
      payloadJson: '{}',
      createdAt: 'SERVER_TIME',
    },
    expected: 'PERMISSION_DENIED',
  },
  {
    id: 11,
    name: 'Post-Creation Scan Mutation',
    path: '/users/user_A/scans/scan_1',
    op: 'update',
    authUid: 'user_A',
    emailVerified: true,
    payload: {
      id: 'scan_1',
      ownerId: 'user_A',
      title: 'Essay',
      wordCount: 100,
      overallScore: 100,
      plagiarismScore: 0,
      paraphraseScore: 0,
      aiScore: 0,
      originalScore: 100,
      summary: 'Tampered',
      payloadJson: '{}',
      createdAt: 'SERVER_TIME',
    },
    expected: 'PERMISSION_DENIED',
  },
  {
    id: 12,
    name: 'Unauthorized Cross-User Scan Listing',
    path: '/users/user_A/scans',
    op: 'list',
    authUid: 'user_B',
    emailVerified: true,
    payload: null,
    expected: 'PERMISSION_DENIED',
  },
];
